services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    ports:
      - "8123:8123"   # HTTP
      - "9002:9000"   # Native
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data/ch:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      - CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse
    volumes:
      - ./data/metabase:/metabase-data